name: "My first next pipeline"

# Create a new pipeline trigger
on:
  push:
    branches:
      - main

      #Sets permissions og the github_token to allow deployment to the gh-pages branch
permissions:
   contents: read
   pages: write
   id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                    node-version: 18
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v3

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build 

            - name: Artifacts
              uses: actions/upload-pages-artifact@v2
              with:
                path: ./out
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
          name: github-pages 
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
          - name: Deploy to Github actions
            id: deployment
            uses: actions/deploy-pages@v2
           
